default_config:

homeassistant:
  packages: !include_dir_named packages

automation manual: !include_dir_merge_list custom_automations
automation ui: !include automations.yaml
script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes
template: !include_dir_merge_list templates