services:
  home-assistant:
    container_name: home-assistant
    image:  ghcr.io/home-assistant/home-assistant:2025.10
    volumes:
      - ${VOLUMES_DIR}/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - mosquitto
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.22
    volumes:
      - ${VOLUMES_DIR}/mosquitto/config:/mosquitto/config
      - ${VOLUMES_DIR}/mosquitto/data:/mosquitto/data
      - ${VOLUMES_DIR}/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    network_mode: host

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.6.2
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-06_f2c016c707adef118d468a4ba8793231-if00-port0:/dev/ttyUSB0
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMES_DIR}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    network_mode: host
    group_add:
      - "dialout"  # Give access to serial devices
      - "tty"      # Give access to serial devices

  zwavejs-ui:
    container_name: zwavejs-ui
    image: zwavejs/zwave-js-ui:11.5.2
    restart: unless-stopped
    depends_on:
      - mosquitto
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/zwave
    environment:
      - TZ=Europe/Amsterdam
      - MQTT_PUBLISH_SET_COMMANDS=true
    volumes:
      - ${VOLUMES_DIR}/zwave-js-ui/store:/usr/src/app/store
    network_mode: host
    group_add:
      - "dialout"  # Give access to serial devices
      - "tty"      # Give access to serial devices

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - ${VOLUMES_DIR}/uptime-kuma/data:/app/data
    network_mode: host

  signal-api:
    container_name: signal-api
    image: bbernhard/signal-cli-rest-api:latest
    restart: unless-stopped
    environment:
      - MODE=native
      - PORT=8081
    volumes:
      - ${VOLUMES_DIR}/signal-api/data:/home/.local/share/signal-cli
    network_mode: host
