services:
  grafana:
    container_name: grafana
    image: grafana/grafana:11.4.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana-config/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki
      - prometheus

  loki:
    container_name: loki
    image: grafana/loki:3.3.2
    restart: unless-stopped
    network_mode: host
    volumes:
      - loki-data:/loki
      - ./loki-config/loki.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=4320h
      - --storage.tsdb.retention.size=50GB
      - --web.enable-remote-write-receiver

volumes:
  grafana-data:
  loki-data:
  prometheus-data:
